import {StyleSheet} from 'react-native';
import {CARD_WIDTH} from './constants';

export const styles = StyleSheet.create({
  // Gallery styles
  galleryContainer: {
    flex: 1,
    backgroundColor: '#0d1117',
  },
  galleryHeader: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#21262d',
  },
  galleryTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#f0f6fc',
    marginBottom: 4,
  },
  gallerySubtitle: {
    fontSize: 14,
    color: '#8b949e',
  },
  galleryList: {
    padding: 12,
  },
  galleryRow: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modelCard: {
    width: CARD_WIDTH,
    backgroundColor: '#161b22',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#30363d',
  },
  modelThumbnail: {
    width: '100%',
    height: 80,
    backgroundColor: '#21262d',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  modelEmoji: {
    fontSize: 40,
  },
  modelName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#f0f6fc',
    marginBottom: 2,
  },
  modelDesc: {
    fontSize: 11,
    color: '#8b949e',
    marginBottom: 8,
  },
  modelActions: {
    flexDirection: 'row',
    gap: 6,
  },
  arActionBtn: {
    flex: 1,
    backgroundColor: '#238636',
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  vrActionBtn: {
    flex: 1,
    backgroundColor: '#1f6feb',
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  actionBtnText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
  },

  // Viewer styles
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  sceneContainer: {
    flex: 1,
  },
  engineView: {
    flex: 1,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  loadingText: {
    color: '#4FC3F7',
    fontSize: 16,
    marginTop: 12,
    fontWeight: 'bold',
  },
  statusBar: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 10,
    borderRadius: 8,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  backButton: {
    backgroundColor: '#30363d',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    marginRight: 8,
  },
  backButtonText: {
    color: '#58a6ff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  modelTitle: {
    flex: 1,
    color: '#f0f6fc',
    fontSize: 15,
    fontWeight: 'bold',
  },
  modeBadge: {
    backgroundColor: '#238636',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  modeBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  statusText: {
    color: '#ffffff',
    fontSize: 12,
  },
  trackingText: {
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  controls: {
    position: 'absolute',
    bottom: 70,
    left: 10,
    right: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  xrButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 25,
    elevation: 5,
    minWidth: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  xrButtonInactive: {
    backgroundColor: '#2196F3',
  },
  xrButtonActive: {
    backgroundColor: '#f44336',
  },
  xrButtonDisabled: {
    backgroundColor: '#555555',
    opacity: 0.6,
  },
  xrButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  infoBar: {
    position: 'absolute',
    top: 110,
    left: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 8,
    borderRadius: 6,
  },
  infoText: {
    color: '#cccccc',
    fontSize: 11,
  },
  createBtn: {
    backgroundColor: '#4CAF50',
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  createBtnText: {
    fontSize: 22,
  },
  instanceActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  actionBtnEqual: {
    backgroundColor: '#ff9800',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 25,
    minWidth: 90,
    alignItems: 'center',
  },
  actionBtnEqualText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
  },
  iconBtnText: {
    fontSize: 20,
  },
  textureBtnBg: {
    backgroundColor: '#7B1FA2',
  },
  texturePanel: {
    position: 'absolute',
    bottom: 130,
    left: 10,
    right: 10,
    backgroundColor: 'rgba(10,0,30,0.92)',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#7B1FA2',
  },
  texturePanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  texturePanelTitle: {
    color: '#CE93D8',
    fontSize: 14,
    fontWeight: 'bold',
  },
  texturePanelClose: {
    color: '#CE93D8',
    fontSize: 18,
    fontWeight: 'bold',
    paddingHorizontal: 8,
  },
  meshSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: 'rgba(123,31,162,0.25)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  meshNavBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  meshNavBtnText: {
    color: '#CE93D8',
    fontSize: 16,
    fontWeight: 'bold',
  },
  meshNameText: {
    flex: 1,
    color: '#f0f6fc',
    fontSize: 12,
    textAlign: 'center',
  },
  meshCountText: {
    color: '#8b949e',
    fontSize: 11,
    marginRight: 4,
  },
  presetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
  },
  presetBtn: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    minWidth: 68,
    alignItems: 'center',
  },
  presetOriginalBg: {
    backgroundColor: '#30363d',
  },
  presetRestoreBg: {
    backgroundColor: '#30363d',
  },
  presetTextureBg: {
    backgroundColor: 'rgba(123,31,162,0.45)',
  },
  presetMaterialBg: {
    backgroundColor: 'rgba(30,90,160,0.45)',
  },
  presetEmoji: {
    fontSize: 18,
    marginBottom: 2,
  },
  presetBtnText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  // Tab bar for texture/material switcher
  tabBar: {
    flexDirection: 'row',
    marginBottom: 8,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(123,31,162,0.5)',
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 7,
    alignItems: 'center',
    backgroundColor: 'rgba(30,0,60,0.6)',
  },
  tabBtnActive: {
    backgroundColor: 'rgba(123,31,162,0.55)',
  },
  tabBtnText: {
    color: 'rgba(200,180,220,0.7)',
    fontSize: 12,
    fontWeight: '600',
  },
  tabBtnTextActive: {
    color: '#fff',
  },
  manipulatorPanel: {
    position: 'absolute',
    bottom: 8,
    left: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,30,0.85)',
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3388ff',
  },
  manipBtnRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  manipPropBtn: {
    backgroundColor: '#335599',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
  },
  manipPropBtnText: {
    color: '#aaccff',
    fontSize: 13,
    fontWeight: 'bold',
  },
  manipActiveRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  manipStepBtn: {
    backgroundColor: '#335599',
    width: 50,
    height: 44,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  manipStepBtnText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: 'bold',
  },
  manipActiveLabel: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
    minWidth: 120,
    textAlign: 'center',
  },
  deselectBtn: {
    backgroundColor: '#883333',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  deselectBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Modern 2D Compass styles
  compassContainer: {
    position: 'absolute',
    top: 150,
    right: 12,
    alignItems: 'center',
    zIndex: 50,
  },
  compassOuter: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(10, 15, 30, 0.8)',
    borderWidth: 1.5,
    borderColor: 'rgba(100, 160, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  compassRose: {
    width: 58,
    height: 58,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  compassLine: {
    position: 'absolute',
    backgroundColor: 'rgba(120, 160, 220, 0.25)',
  },
  compassLineNS: {
    width: 1,
    height: '100%',
    left: '50%',
    marginLeft: -0.5,
  },
  compassLineEW: {
    width: '100%',
    height: 1,
    top: '50%',
    marginTop: -0.5,
  },
  compassCardinal: {
    position: 'absolute',
  },
  compassN: {
    color: '#ff4444',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  compassLetter: {
    color: 'rgba(200, 210, 230, 0.85)',
    fontSize: 10,
    fontWeight: '600',
    textAlign: 'center',
  },
  compassNorthPointer: {
    position: 'absolute',
    top: 12,
    left: '50%',
    marginLeft: -4,
    width: 0,
    height: 0,
    borderLeftWidth: 4,
    borderRightWidth: 4,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#ff4444',
  },
  compassCenterDot: {
    position: 'absolute',
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#64a0ff',
  },
  compassFixedArrow: {
    position: 'absolute',
    top: -1,
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#64a0ff',
  },
  compassDegreeText: {
    color: 'rgba(200, 220, 255, 0.9)',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
    textAlign: 'center',
  },
  // Source header in cross-model texture panel
  sourceHeader: {
    backgroundColor: 'rgba(123,31,162,0.35)',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    marginBottom: 6,
    marginTop: 4,
  },
  sourceHeaderText: {
    color: '#CE93D8',
    fontSize: 11,
    fontWeight: 'bold',
  },
});
