import {StyleSheet, Platform, Dimensions} from 'react-native';
import {CARD_WIDTH} from './constants';

const {width} = Dimensions.get('window');

const COLORS = {
  background: '#09090b',
  cardBg: '#18181b',
  cardBorder: '#27272a',
  primary: '#3b82f6',
  success: '#22c55e',
  textMain: '#ffffff',
  textSec: '#a1a1aa',
  panelBg: 'rgba(24, 24, 27, 0.95)',
  accentPurple: '#a855f7',
  danger: '#ef4444',
  disabled: '#3f3f46',
};

export const styles = StyleSheet.create({

  // ================= GALLERIA =================
  galleryContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  galleryHeader: {
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
    paddingBottom: 16,
    backgroundColor: COLORS.background,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.cardBorder,
  },
  galleryTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: COLORS.textMain,
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  gallerySubtitle: {
    fontSize: 14,
    color: COLORS.textSec,
    fontWeight: '500',
  },
  galleryList: {
    padding: 16,
    paddingBottom: 40,
  },
  galleryRow: {
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modelCard: {
    width: CARD_WIDTH,
    height: 250,
    backgroundColor: COLORS.cardBg,
    borderRadius: 20,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
    justifyContent: 'space-between',
  },
  modelThumbnail: {
    width: '100%',
    height: 110,
    backgroundColor: '#000',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
  },
  modelEmoji: {
    fontSize: 50,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: {width: 0, height: 2},
    textShadowRadius: 4,
  },
  cardTextContainer: {
    height: 65, 
    marginBottom: 4,
    justifyContent: 'flex-start',
  },
  modelName: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textMain,
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  modelDesc: {
    fontSize: 12,
    color: COLORS.textSec,
    lineHeight: 16,
    fontWeight: '500',
  },
  marqueeContainer: {
    overflow: 'hidden',
    width: '100%',
    height: 24,
  },
  
  // Layout pulsanti galleria (Row)
  modelActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 'auto',
  },
  arActionBtn: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.success,
    gap: 6,
  },
  vrActionBtn: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.primary,
    gap: 6,
  },
  actionBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  sceneContainer: {
    flex: 1,
  },
  engineView: {
    flex: 1,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  loadingText: {
    color: COLORS.primary,
    fontSize: 16,
    marginTop: 16,
    fontWeight: '600',
  },
  statusBar: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 10 : 10,
    left: 16,
    right: 16,
    backgroundColor: COLORS.panelBg,
    paddingVertical: 8, 
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.4,
    shadowRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 50,
  },
  statusLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    overflow: 'hidden',
    marginRight: 10,
  },
  backButton: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: 8,
    borderRadius: 10,
    marginRight: 12,
  },
  modelTitle: {
    color: COLORS.textMain,
    fontSize: 16,
    fontWeight: '700',
  },
  statusRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modeBadge: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  modeBadgeText: {
    color: COLORS.textMain,
    fontSize: 10,
    fontWeight: '800',
  },

  // Controlli
  controls: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 50,
  },
  actionGroup: {
    flexDirection: 'row',
    backgroundColor: COLORS.panelBg,
    borderRadius: 24,
    padding: 6,
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    elevation: 5,
  },
  iconBtn: {
    width: 48,
    height: 48,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  iconBtnActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.25)',
    borderColor: COLORS.primary,
    borderWidth: 1,
  },
  iconBtnDestructive: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderColor: 'rgba(239, 68, 68, 0.5)',
    borderWidth: 1,
  },
  iconBtnDisabled: {
    opacity: 0.2,
  },
  
  // Pulsante stabilizzazione VR
  vrStabilizeBtn: {
    backgroundColor: 'rgba(59, 130, 246, 0.8)',
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    elevation: 5,
    shadowColor: COLORS.primary,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  vrStabilizeBtnActive: {
    backgroundColor: 'rgba(234, 179, 8, 0.9)',
    borderColor: '#facc15',
    borderWidth: 2,
    shadowColor: '#facc15',
    shadowOpacity: 0.7,
  },

  createBtn: {
    backgroundColor: COLORS.success,
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
    shadowColor: COLORS.success,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 8,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  createBtnDisabled: {
    backgroundColor: 'rgba(100, 100, 100, 0.5)',
    borderColor: 'rgba(150, 150, 150, 0.3)',
    shadowOpacity: 0,
    elevation: 0,
  },

  // ================= PANNELLO TEXTURE =================
  texturePanel: {
    position: 'absolute',
    bottom: 110,
    left: 16,
    right: 16,
    backgroundColor: COLORS.panelBg,
    padding: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.accentPurple,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -4},
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  texturePanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
    paddingBottom: 8,
  },
  texturePanelTitle: {
    color: '#e9d5ff',
    fontSize: 16,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  meshSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  meshNavBtn: {
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
  },
  meshNameText: {
    flex: 1,
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  
  // Stili per i preset (più piccoli e su una riga)
  presetScrollView: {
    maxHeight: 70, // Altezza limitata per la scroll view orizzontale
  },
  presetGrid: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 2,
  },
  presetBtn: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    minWidth: 50,
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  presetBtnSelected: {
    borderColor: COLORS.accentPurple, // Bordo viola SOLO se selezionato
    backgroundColor: 'rgba(168, 85, 247, 0.15)',
    borderWidth: 1.5,
  },
  presetEmoji: { fontSize: 18, marginBottom: 2 },
  presetBtnText: { color: '#fff', fontSize: 9, fontWeight: '700' },
  tabBar: {
    flexDirection: 'row',
    marginBottom: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.4)',
    padding: 4,
  },
  tabBtn: { flex: 1, paddingVertical: 6, alignItems: 'center', borderRadius: 8 },
  tabBtnActive: { backgroundColor: 'rgba(255,255,255,0.1)' },
  tabBtnText: { color: '#71717a', fontSize: 12, fontWeight: '600' },
  tabBtnTextActive: { color: '#fff' },

  // ================= MANIPOLATORE =================
  manipulatorPanel: {
    position: 'absolute',
    bottom: 110,
    left: 20,
    right: 20,
    backgroundColor: COLORS.panelBg,
    padding: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  manipBtnRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
    flexWrap: 'wrap',
  },
  manipPropBtn: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    minWidth: 50,
    alignItems: 'center',
  },
  manipPropBtnText: { color: '#fff', fontSize: 11, fontWeight: '600' },
  manipActiveRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  manipStepBtn: {
    backgroundColor: COLORS.primary,
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  manipStepBtnText: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  manipActiveLabel: { color: '#fff', fontSize: 16, fontWeight: '700', minWidth: 100, textAlign: 'center' },
  closeManipBtn: {
    position: 'absolute',
    top: -10,
    right: -10,
    backgroundColor: COLORS.cardBg,
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#333',
  },

  // ================= BUSSOLA 2D =================
  compassContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 70 : 50,
    right: 16,
    alignItems: 'center',
    zIndex: 50,
  },
  compassOuter: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  compassRose: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  compassLine: { position: 'absolute', backgroundColor: 'rgba(255, 255, 255, 0.2)' },
  compassLineNS: { width: 1, height: '100%', left: '50%' },
  compassLineEW: { width: '100%', height: 1, top: '50%' },
  compassCardinal: { position: 'absolute' },
  
  // N/S/E/W sono sullo sfondo
  compassN: { color: COLORS.danger, fontSize: 10, fontWeight: '900', top: 2, left: '50%', marginLeft: -3, zIndex: 1 },
  compassS: { color: COLORS.textSec, fontSize: 9, fontWeight: '700', bottom: 2, left: '50%', marginLeft: -3, zIndex: 1 },
  compassE: { color: COLORS.textSec, fontSize: 9, fontWeight: '700', right: 3, top: '50%', marginTop: -5, zIndex: 1 },
  compassW: { color: COLORS.textSec, fontSize: 9, fontWeight: '700', left: 3, top: '50%', marginTop: -5, zIndex: 1 },
  compassNorthPointer: {
    position: 'absolute',
    top: 9, // Spostata un po' più giù per non toccare la N (di Nord)
    left: '50%',
    marginLeft: -3,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderBottomWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: COLORS.danger,
    zIndex: 2,
  },
  compassCenterDot: { position: 'absolute', width: 3, height: 3, borderRadius: 1.5, backgroundColor: '#fff', zIndex: 3 },
  
  // Freccia Bianca Fissa (Sempre sopra)
  compassFixedArrow: {
    position: 'absolute',
    top: -2,
    borderLeftWidth: 4,
    borderRightWidth: 4,
    borderBottomWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#fff',
    zIndex: 4,
  },
  compassDegreeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '700',
    marginTop: 4,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 4,
    borderRadius: 4,
  },
});